#! /bin/bash
## My custom spaces
yabai -m space 1 --label Anthing
yabai -m space 2 --label Web
yabai -m space 3 --label Code

## float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^Mini Program$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off

## New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost off

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.00
# yabai -m config active_window_opacity 1.0

## set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
## set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
## set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xFFFF9500
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color      0xffd75f5f

## Change how yabai looks
yabai -m config layout bsp
## Override default layout for space 2 only
yabai -m config --space 1 layout float

# Set all padding and gaps to 12pt (default: 0)
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:28:0

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash ~/.config/yabai/window-focus-on-destroy.sh"

echo "yabai configuration loaded.."

## END
