#!/usr/bin/env bash

if ! command -v stow > /dev/null
then
  echo "Command not found: stow. Please install it before syncing symbolic links"
  echo "Refer to https://www.gnu.org/software/stow/ for more detail"
  exit 1
fi

CHECK_MARK="\033[0;32m󰄬\033[0m"

DOT_DIR="$(dirname $(readlink -f "$0"))/dotfiles"

PKGS_TO_STOW=()
if [ $# -gt 0 ]; then
  for item in "$@"; do
    if [ -d "${DOT_DIR}/${item}" ]; then
      PKGS_TO_STOW+=("$item")
    else
      echo -e "Error: Package '${item}' not found in $DOT_DIR\n"
    fi
  done
else
  PKGS_TO_STOW=($(ls $DOT_DIR))
fi

if [ ${#PKGS_TO_STOW[@]} -eq 0 ]; then
  echo -e "No packages found to process in $DOT_DIR\n"
  exit 2
else
  # Symlinks all the dotfiles into your home directory
  echo -e "Syncing symbolic links for dotfiles in ${#PKGS_TO_STOW[@]} packages...\n"
fi


function clear_line() {
  if [ -n "$TTY" ]; then
    COLUMNS=$(stty size | awk '{print $2}')
  fi
  echo -en "\r$(eval "printf ' %.0s' {1..${COLUMNS:-0}}")"
}

function create_link() {
  echo -en "- Stowing $1 ..."

  stow $1 --no-folding

  clear_line
  echo -e "\r$CHECK_MARK $1 stowed"
}

cd $DOT_DIR > /dev/null

for item in "${PKGS_TO_STOW[@]}"; do
  create_link $item
done

cd - > /dev/null

echo -e "\nDone!"

if [ -f "${HOME}/.gitconfig.common" ]; then
  git config --global include.path "${HOME}/.gitconfig.common"
fi

if [ -d "${HOME}/.ssh/config.d" ]; then
  INCLUDE_CONTENT="Include ~/.ssh/config.d/*"
  SSH_CONFIG="${HOME}/.ssh/config"

  touch $SSH_CONFIG

  if ! grep -qxF "$INCLUDE_CONTENT" "$SSH_CONFIG" 2>/dev/null; then
    { printf "%s\n\n" "$INCLUDE_CONTENT"; cat $SSH_CONFIG; } > ${SSH_CONFIG}.tmp

    mv ${SSH_CONFIG}.tmp $SSH_CONFIG
  fi
fi
