# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

keymap = [
  { on = ["<Esc>"], run = "escape --all", desc = "Exit visual mode, clear selected, or cancel search" },
  { on = ["q"], run = "quit", desc = "Exit the process" },
  { on = ["<C-c>"], run = "quit", desc = "Exit the process" },

  # Navigation
  { on = ["k"], run = "arrow -1", desc = "Move cursor up" },
  { on = ["j"], run = "arrow 1", desc = "Move cursor down" },
  { on = ["<C-u>"], run = "arrow -50%", desc = "Move cursor up half page" },
  { on = ["<C-d>"], run = "arrow 50%", desc = "Move cursor down half page" },
  { on = ["G"], run = "arrow 99999999", desc = "Move cursor to the bottom" },
  { on = ["g", "g"], run = "arrow -99999999", desc = "Move cursor to the top" },
  { on = ["g", "h"], run = "cd ~", desc = "Go to the home directory" },
  { on = ["g", "<Space>"], run = "cd --interactive", desc = "Go to a directory interactively" },


  { on = ["h"], run = "leave", desc = "Go back to the parent directory" },
  { on = ["l"], run = "enter", desc = "Enter the child directory" },

  { on = ["˚"], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["∆"], run = "seek 5", desc = "Seek down 5 units in the preview" },

  # Selection
  { on = ["<Space>"], run = ["select --state=none", "arrow 1"], desc = "Toggle the current selection state" },
  { on = ["v"], run = "visual_mode", desc = "Enter visual mode (selection mode)" },
  { on = ["V"], run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },
  { on = ["<C-a>"], run = "select_all --state=true", desc = "Select all files" },
  { on = ["<C-r>"], run = "select_all --state=none", desc = "Inverse selection of all files" },

  # Operation
  { on = ["o"], run = "open", desc = "Open the selected files" },
  { on = ["O"], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = ["<Enter>"], run = "open --interactive", desc = "Open the selected files" },
  { on = ["n"], run = "create", desc = "Create a file or directory (ends with / for directories)" },
  { on = ["r"], run = "rename --cursor=before_ext", desc = "Rename a file or directory" },
  { on = ["H"], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  { on = ["d", "d"], run = "remove", desc = "Move the files to the trash" },
  { on = ["d", "D"], run = "remove --permanently", desc = "Permanently delete the files" },
  { on = ["<C-t>"], run = "plugin fzf", desc = "Jump to a directory, or reveal a file using fzf" },

  # Yank/Cut/Paste
  { on = ["y", "y"], run = "yank", desc = "Copy the selected files" },
  { on = ["y", "p"], run = "copy path", desc = "Copy the absolute path" },
  { on = ["y", "d"], run = "copy dirname", desc = "Copy the path of the parent directory" },
  { on = ["y", "f"], run = "copy filename", desc = "Copy the name of the file" },
  { on = ["y", "n"], run = "copy name_without_ext", desc = "Copy the name of the file without the extension" },
  { on = ["p"], run = "paste", desc = "Paste the files" },
  { on = ["P"], run = "paste --force", desc = "Paste the files (overwrite if the destination exists)" },
  { on = ["x"], run = "yank --cut", desc = "Cut the selected files" },

  # Search
  { on = ["/"], run = "find --smart", desc = "Filter the files" },
  { on = ["<C-p>"], run = "search fd", desc = "Search files by name using fd" },

  # Tabs
  { on = ["t"], run = "tab_create --current", desc = "Create a new tab using the current path" },

  { on = ["1"], run = "tab_switch 0", desc = "Switch to the first tab" },
  { on = ["2"], run = "tab_switch 1", desc = "Switch to the second tab" },
  { on = ["3"], run = "tab_switch 2", desc = "Switch to the third tab" },
  { on = ["4"], run = "tab_switch 3", desc = "Switch to the fourth tab" },
  { on = ["5"], run = "tab_switch 4", desc = "Switch to the fifth tab" },
  { on = ["6"], run = "tab_switch 5", desc = "Switch to the sixth tab" },
  { on = ["7"], run = "tab_switch 6", desc = "Switch to the seventh tab" },
  { on = ["8"], run = "tab_switch 7", desc = "Switch to the eighth tab" },
  { on = ["9"], run = "tab_switch 8", desc = "Switch to the ninth tab" },

  { on = ["<Tab>"], run = "tab_switch 1 --relative", desc = "Switch to the next tab" },

  # Help
  { on = ["?"], run = "help", desc = "Open help" },
]

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"
