
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "catppuccin-mocha"

[mgr]

border_symbol = "│"
border_style  = { fg = "black" }

syntect_theme = "~/.config/bat/themes/Catppuccin Mocha.tmTheme"

preview_hovered = { underline = false }

[tabs]
# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
