#! /usr/bin/env zsh

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
fi

filename="${1:-}"

get_filename() {
  local input=""
  local is_existed="1"

  while [[ ! -z "$is_existed" ]]; do
    if [[ -z "$input" ]]; then
      read -r "input?Enter a filename: "
    else
      read -r "input?File existed. Enter another name: "
    fi

    is_existed=$(fd --type f "$input.md" "$OBSIDIAN_VAULT")
  done

  filename="$input"
}

open_file() {
  # Enter the directory
  cd "$1" || exit

  file="$1/$filename.md"
  touch "$file"

  today=$(date +"%Y-%m-%d")

  # Append content to the file
  {
    echo "# $(title $filename)"
    echo ""
    echo ""
    echo ""
    echo "##### Links"
    echo ""
    echo "[[$today|Created at $today $(date +"%H:%M")]]"
  } > "$file"

  nvim '+ normal ggzz2j' "$file"
}

if [[ -z "$filename" ]]; then
  get_filename
fi

open_file "$OBSIDIAN_VAULT/0-inbox"
