#!/usr/bin/env sh

__TM_DEFAULT_PLUGINS_DIR="$HOME/.tmux"
__TM_TPM_DIR="$__TM_DEFAULT_PLUGINS_DIR/tpm"

__TM_AUTO_INSTALL=0
if [ ! -d "$__TM_TPM_DIR" ]; then
  # Download the TPM if not existed
  git clone --depth 1 https://github.com/tmux-plugins/tpm $__TM_TPM_DIR
  __TM_AUTO_INSTALL=1
fi

tmux run "$__TM_TPM_DIR/tpm"

if [ "$__TM_AUTO_INSTALL" = 1 ]; then
  # Auto install the missing plugins on start
  tmux run "$__TM_TPM_DIR/bin/install_plugins" \; source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"
fi
