#!/bin/env sh

# foot server daemon
riverctl spawn "${HOME}/.local/bin/foots"

# wl-clipboard
clipboard_cmd="wl-paste --watch cliphist store"
pgrep -f "$clipboard_cmd" || riverctl spawn "$clipboard_cmd"

# dam
riverctl spawn "${HOME}/.local/bin/dam-run"

# wob
pgrep "wob" || riverctl spawn "${HOME}/.local/bin/wobd"

# background image
killall "swaybg" > /dev/null 2>&1; riverctl spawn "swaybg -i ${HOME}/.local/share/wallpaper -m fill"

# input method - fcitx5
killall "fcitx5" > /dev/null 2>&1; riverctl spawn "fcitx5 -d"

# Idle management
pgrep "swayidle" || riverctl spawn "swayidle"

# Dynamic display configuration
killall "kanshi" > /dev/null 2>&1; riverctl  spawn "kanshi"
