#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

. $HOME/.config/river/autostart
. $HOME/.config/river/keymaps

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xE45C9C
riverctl border-color-unfocused 0xFFFFFF00
riverctl border-width 2

# Window rules
# Fix the border for every window
riverctl rule-add -app-id '*' ssd

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd


# Set keyboard repeat rate
riverctl set-repeat 30 200

riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 12 -outer-padding 12 &
