#!/bin/env sh

# Note: the "${mod}" modifier is also known as Logo, GUI, Windows, Mod4, etc.
# Mod1=Alt Mod4=Super
mod=Super

term=footclient

# ${mod}+Shift+r to reload the river config
riverctl map normal ${mod}+Shift r spawn "${HOME}/.config/river/init"

# ${mod}+Q to close the focused view
riverctl map normal ${mod} Q close

# ${mod}+Shift+E to exit river
riverctl map normal ${mod}+Shift+Control E spawn "${HOME}/.local/bin/exit-river"

# ${mod}+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal ${mod} J focus-view next
riverctl map normal ${mod} K focus-view previous

# ${mod}+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal ${mod}+Shift J swap next
riverctl map normal ${mod}+Shift K swap previous

# ${mod}+Period and Super+Comma to focus the next/previous output
riverctl map normal ${mod} Period focus-output next
riverctl map normal ${mod} Comma focus-output previous

# ${mod}+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal ${mod}+Shift Period send-to-output next
riverctl map normal ${mod}+Shift Comma send-to-output previous

# ${mod}+Return to bump the focused view to the top of the layout stack
riverctl map normal ${mod} Return zoom

# ${mod}+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal ${mod} H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal ${mod} L send-layout-cmd rivertile "main-ratio +0.05"

# ${mod}+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal ${mod}+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal ${mod}+Shift L send-layout-cmd rivertile "main-count -1"

# ${mod}+Alt+{H,J,K,L} to move views
riverctl map normal ${mod}+Alt H move left 100
riverctl map normal ${mod}+Alt J move down 100
riverctl map normal ${mod}+Alt K move up 100
riverctl map normal ${mod}+Alt L move right 100

# ${mod}+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal ${mod}+Alt+Control H snap left
riverctl map normal ${mod}+Alt+Control J snap down
riverctl map normal ${mod}+Alt+Control K snap up
riverctl map normal ${mod}+Alt+Control L snap right

# ${mod}+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal ${mod}+Alt+Shift H resize horizontal -100
riverctl map normal ${mod}+Alt+Shift J resize vertical 100
riverctl map normal ${mod}+Alt+Shift K resize vertical -100
riverctl map normal ${mod}+Alt+Shift L resize horizontal 100

# ${mod} + Left Mouse Button to move views
riverctl map-pointer normal ${mod} BTN_LEFT move-view

# ${mod} + Right Mouse Button to resize views
riverctl map-pointer normal ${mod} BTN_RIGHT resize-view

# ${mod} + Middle Mouse Button to toggle float
riverctl map-pointer normal ${mod} BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # ${mod}+[1-9] to focus tag [0-8]
    riverctl map normal ${mod} $i set-focused-tags $tags

    # ${mod}+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal ${mod}+Shift $i set-view-tags $tags

    # ${mod}+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal ${mod}+Control $i toggle-focused-tags $tags

    # ${mod}+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal ${mod}+Shift+Control $i toggle-view-tags $tags
done

# ${mod}+0 to focus all tags
# ${mod}+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal ${mod} 0 set-focused-tags $all_tags
riverctl map normal ${mod}+Shift 0 set-view-tags $all_tags

# ${mod}+Space to list run menu
riverctl map normal ${mod} Space spawn "${HOME}/.local/bin/wmenu-run-color" 

# ${mod}+F to toggle fullscreen
riverctl map normal ${mod} F toggle-fullscreen

# ${mod}+{Up,Right,Down,Left} to change layout orientation
riverctl map normal ${mod} Up    send-layout-cmd rivertile "main-location top"
riverctl map normal ${mod} Right send-layout-cmd rivertile "main-location right"
riverctl map normal ${mod} Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal ${mod} Left  send-layout-cmd rivertile "main-location left"

# VolumeUp/VolumeDown/Mute for the audio control
riverctl map -repeat normal None XF86AudioRaiseVolume spawn "${HOME}/.local/bin/audio sink --plus"
riverctl map -repeat normal None XF86AudioLowerVolume spawn "${HOME}/.local/bin/audio sink --minus"
riverctl map normal None XF86AudioMute spawn "${HOME}/.local/bin/audio sink --mute"

# ${mod}+C to list the clipboard history
riverctl map normal ${mod} C spawn "${HOME}/.local/bin/wclip"

riverctl map normal None XF86MonBrightnessUp spawn "${HOME}/.local/bin/bright --plus"
riverctl map normal None XF86MonBrightnessDown spawn "${HOME}/.local/bin/bright --minus"

riverctl map normal ${mod}+Control Q spawn "swaylock"

# Control+Space to switch between input methods
riverctl map normal Control Space spawn "fcitx5-remote -t"

riverctl map normal ${mod}+Shift T spawn "${term} -T float_term -w 1400x800 tmux-floatx"
