#!/bin/bash
## Refer to: https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc

## Focus window
ctrl + alt - h : yabai -m window --focus west || yabai -m window --focus last
ctrl + alt - j : yabai -m window --focus south || yabai -m window --focus first
ctrl + alt - k : yabai -m window --focus north || yabai -m window --foccus last
ctrl + alt - l : yabai -m window --focus east || yabai -m window --focus first

## Swap
ctrl + alt - left : sh ~/.config/skhd/window-action.sh swap west
ctrl + alt - down : sh ~/.config/skhd/window-action.sh swap south
ctrl + alt - up : sh ~/.config/skhd/window-action.sh swap north
ctrl + alt - right : sh ~/.config/skhd/window-action.sh swap east

## Toggle window fullscreen zoom
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen

## Focus display
ctrl + alt - 1 : sh ~/.config/skhd/focus-display.sh 1
ctrl + alt - 2 : sh ~/.config/skhd/focus-display.sh 2

## Focus window up/down in stack
ctrl + alt - n : yabai -m window --focus stack.next || yabai -m window --focus stack.first
ctrl + alt - p : yabai -m window --focus stack.prev || yabai -m window --focus stack.last

## Send window and follow focus
# * Save current window ID as CUR_WIN
# * Move the window to prev/next display
# * Focus the window by given ID
ctrl + alt - 0x21 : sh ~/.config/skhd/send-window-to-display.sh prev # 0x21 = [
ctrl + alt - 0x1E : sh ~/.config/skhd/send-window-to-display.sh next # 0x1E = ]

## Send window to space and follow focus
shift + alt - 1 : sh ~/.config/skhd/send-window-to-space.sh 1
shift + alt - 2 : sh ~/.config/skhd/send-window-to-space.sh 2
shift + alt - 3 : sh ~/.config/skhd/send-window-to-space.sh 3
shift + alt - 4 : sh ~/.config/skhd/send-window-to-space.sh 4
shift + alt - 5 : sh ~/.config/skhd/send-window-to-space.sh 5


## Switch layout
shift + alt - f : yabai -m space --layout float
shift + alt - t : yabai -m space --layout bsp

shift + alt - space : yabai -m window --toggle float --grid 4:4:1:1:2:2
shift + alt - s : yabai -m window --toggle split

## Rotate
shift + alt - r : yabai -m space --rotate 90

## Balance window
shift + alt - 0x18 : yabai -m space --balance # 0x18 is the "=" key

## Resize current window
shift + alt - h : yabai -m window --resize left:-50:0 || yabai -m window --resize right:-50:0
shift + alt - j : yabai -m window --resize bottom:0:50 || yabai -m window --resize top:0:50
shift + alt - k : yabai -m window --resize top:0:-50 || yabai -m window --resize bottom:0:-50
shift + alt - l : yabai -m window --resize right:50:0 || yabai -m window --resize left:50:0

## Add the active window to the window or stack to the {direction}
## Note that this only works when the active window does *not* already belong to a stack
shift + alt - left : sh ~/.config/skhd/window-action.sh stack west
shift + alt - down : sh ~/.config/skhd/window-action.sh stack south
shift + alt - up : sh ~/.config/skhd/window-action.sh stack north
shift + alt - right : sh ~/.config/skhd/window-action.sh stack east

## Services restart
## Yabai
shift + ctrl + alt - y : /usr/bin/osascript <<< "display notification \"Restarting Yabai\" with title \"Yabai\""; \
  brew services restartyabai
## skhd
shift + ctrl + alt - s : /usr/bin/osascript <<< "display notification \"Restarting skhd\" with title \"skhd\""; \
  brew services restart skhd
