#!/bin/bash
## Refer to: https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc

## Open terminal, blazingly fast compared to iTerm/Hyper
# alt - t : CUR_DISP=`yabai -m query --displays --display | /usr/local/bin/jq -r '.index'` && \
#     /Applications/kitty.app/Contents/MacOS/kitty --instance-group=$CUR_DISP --single-instance -d ~ && \
#     unset CUR_DISP
alt - t : /Applications/kitty.app/Contents/MacOS/kitty --instance-group=2 --single-instance -d ~ 

## Focus window
ctrl + alt - h : yabai -m window --focus west || yabai -m window --focus last
ctrl + alt - j : yabai -m window --focus south || yabai -m window --focus first
ctrl + alt - k : yabai -m window --focus north || yabai -m window --foccus last
ctrl + alt - l : yabai -m window --focus east || yabai -m window --focus first

## Toggle window fullscreen zoom
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen

## Focus display
ctrl + alt - 1 : sh ~/.config/skhd/focus-display.sh 1
ctrl + alt - 2 : sh ~/.config/skhd/focus-display.sh 2 

## Focus window up/down in stack
ctrl + alt - n : yabai -m window --focus stack.next || yabai -m window --focus stack.first
ctrl + alt- p : yabai -m window --focus stack.prev || yabai -m window --focus stack.last

## Send window and follow focus
# * Save current window ID as CUR_WIN
# * Move the window to prev/next display
# * Focus the window by given ID
ctrl + alt - 0x21 : sh ~/.config/skhd/send-window-to-display.sh prev
ctrl + alt - 0x1E : sh ~/.config/skhd/send-window-to-display.sh next

## Send window to space and follow focus
shift + alt - 1 : sh ~/.config/skhd/send-window-to-space.sh 1
shift + alt - 2 : sh ~/.config/skhd/send-window-to-space.sh 2
shift + alt - 3 : sh ~/.config/skhd/send-window-to-space.sh 3
shift + alt - 4 : sh ~/.config/skhd/send-window-to-space.sh 4

## Swap
## Refer to: https://github.com/Shufflepuck/MenuLock/blob/master/README.md
shift + alt - 0x21 : yabai -m window --swap west # 0x21 is the "[" key
shift + alt - 0x1E : yabai -m window --swap east # 0x1E is the "]" key

## Switch layout
shift + alt - f : yabai -m space --layout float
shift + alt - t : yabai -m space --layout bsp

## Rotate
shift + alt - r : yabai -m space --rotate 90

## Balance window
shift + alt - 0x18 : yabai -m space --balance # 0x18 is the "=" key

## Focus space
alt - 1 : sh ~/.config/skhd/switch-space.sh 1
alt - 2 : sh ~/.config/skhd/switch-space.sh 2
alt - 3 : sh ~/.config/skhd/switch-space.sh 3
alt - 4 : sh ~/.config/skhd/switch-space.sh 4
alt - 5 : sh ~/.config/skhd/switch-space.sh 5

## Add the active window to the window or stack to the {direction}
## Note that this only works when the active window does *not* already belong to a stack
shift + alt - h  : sh ~/.config/skhd/stack-window.sh west

shift + alt - j  : sh ~/.config/skhd/stack-window.sh south

shift + alt - k  : sh ~/.config/skhd/stack-window.sh north

shift + alt - l  : sh ~/.config/skhd/stack-window.sh east
