#!/bin/bash
## Refer to: https://github.com/koekeishiya/skhd/blob/master/examples/skhdrc

## Focus window
ctrl + alt - h : yabai -m window --focus west || yabai -m window --focus last
ctrl + alt - j : yabai -m window --focus south || yabai -m window --focus first
ctrl + alt - k : yabai -m window --focus north || yabai -m window --foccus last
ctrl + alt - l : yabai -m window --focus east || yabai -m window --focus first

## Swap
ctrl + alt - left : sh ~/.config/skhd/window-action.sh swap west
ctrl + alt - down : sh ~/.config/skhd/window-action.sh swap south
ctrl + alt - up : sh ~/.config/skhd/window-action.sh swap north
ctrl + alt - right : sh ~/.config/skhd/window-action.sh swap east

## Toggle window fullscreen zoom
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen

## Focus display
ctrl + alt - 1 : sh ~/.config/skhd/focus-display.sh 1
ctrl + alt - 2 : sh ~/.config/skhd/focus-display.sh 2

## Focus window up/down in stack
ctrl + alt - n : yabai -m window --focus stack.next || yabai -m window --focus stack.first
ctrl + alt - p : yabai -m window --focus stack.prev || yabai -m window --focus stack.last

## Send window and follow focus
# * Save current window ID as CUR_WIN
# * Move the window to prev/next display
# * Focus the window by given ID
ctrl + alt - 0x21 : sh ~/.config/skhd/send-window-to-display.sh prev # 0x21 = [
ctrl + alt - 0x1E : sh ~/.config/skhd/send-window-to-display.sh next # 0x1E = ]

## Send window to space and follow focus
shift + alt - 1 : sh ~/.config/skhd/send-window-to-space.sh 1
shift + alt - 2 : sh ~/.config/skhd/send-window-to-space.sh 2
shift + alt - 3 : sh ~/.config/skhd/send-window-to-space.sh 3
shift + alt - 4 : sh ~/.config/skhd/send-window-to-space.sh 4
shift + alt - 5 : sh ~/.config/skhd/send-window-to-space.sh 5

## Switch layout
shift + alt - f : yabai -m space --layout float
shift + alt - t : yabai -m space --layout bsp

# Center the float window
shift + alt - c : yabai -m window --grid 4:4:1:1:2:2
# Toggle the current window to float and center it
shift + alt - space : yabai -m window --toggle float --grid 20:20:1:1:18:18
# Split the current row
shift + alt - s : yabai -m window --toggle split

## Rotate
shift + alt - r : yabai -m space --rotate 90

## Resize current window
shift + alt - h : yabai -m window --resize left:-50:0 || yabai -m window --resize right:-50:0
shift + alt - j : yabai -m window --resize bottom:0:50 || yabai -m window --resize top:0:50
shift + alt - k : yabai -m window --resize top:0:-50 || yabai -m window --resize bottom:0:-50
shift + alt - l : yabai -m window --resize right:50:0 || yabai -m window --resize left:50:0

## Window Scaling
# * float window - scale up/down
# * bsp window - balance all windows
shift + alt - 0x18 : sh ~/.config/skhd/window-scale.sh up   # 0x18 = +
shift + alt - 0x1B : sh ~/.config/skhd/window-scale.sh down # 0x1B = -

## Add the active window to the window or stack to the {direction}
## Note that this only works when the active window does *not* already belong to a stack
shift + alt - left : sh ~/.config/skhd/window-action.sh stack west
shift + alt - down : sh ~/.config/skhd/window-action.sh stack south
shift + alt - up : sh ~/.config/skhd/window-action.sh stack north
shift + alt - right : sh ~/.config/skhd/window-action.sh stack east

## Toggle the border to all the windows
# INFO: window border is disabled
# shift + ctrl + alt - space : sh ~/.config/skhd/toggle-window-border.sh

## Switch spaces
alt - 1 : sh ~/.config/skhd/focus-space.sh 1
alt - 2 : sh ~/.config/skhd/focus-space.sh 2
alt - 3 : sh ~/.config/skhd/focus-space.sh 3
alt - 4 : sh ~/.config/skhd/focus-space.sh 4
alt - 5 : sh ~/.config/skhd/focus-space.sh 5
alt - 6 : sh ~/.config/skhd/focus-space.sh 6

## Services restart
## Yabai
shift + ctrl + alt - y : sh ~/.config/skhd/restart-service.sh yabai
## skhd
shift + ctrl + alt - s : sh ~/.config/skhd/restart-service.sh skhd
